# Generated by Django 5.1.7 on 2025-03-07 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_currency_trend'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='')),
                ('priority', models.CharField(default='medium', max_length=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Announcement Archive',
                'verbose_name_plural': 'Announcement Archives',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='CurrencyArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Currency Archive',
                'verbose_name_plural': 'Currency Archives',
                'ordering': ['-archived_at'],
            },
        ),
        migrations.CreateModel(
            name='MarketDataArchive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('value', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('port_sudan', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dmt_china', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dmt_uae', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dmt_mersing', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('dmt_india', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(default='Active', max_length=50)),
                ('forecast', models.CharField(default='Stable', max_length=50)),
                ('trend', models.IntegerField(default=0)),
                ('image_url', models.CharField(blank=True, max_length=255, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
                ('last_update', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'Market Data Archive',
                'verbose_name_plural': 'Market Data Archives',
                'ordering': ['-archived_at'],
            },
        ),
    ]
