# Generated by Django 5.1.7 on 2025-03-07 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_emailotp_purpose_alter_emailotp_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailotp',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailotp',
            name='verification_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='emailotp',
            name='purpose',
            field=models.CharField(choices=[('login', 'Login Verification'), ('registration', 'Registration Verification'), ('password_reset', 'Password Reset'), ('email_change', 'Email Change Verification'), ('security_action', 'Security Action Verification')], default='login', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['email', 'purpose'], name='core_emailo_email_a0bc4e_idx'),
        ),
        migrations.AddIndex(
            model_name='emailotp',
            index=models.Index(fields=['expires_at'], name='core_emailo_expires_d20935_idx'),
        ),
    ]
