# Generated by Django 5.1.7 on 2025-03-10 23:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_emailotp_ip_address_emailotp_user_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('usd_to_sdg', models.DecimalField(decimal_places=2, help_text='Exchange rate USD to SDG', max_digits=10)),
            ],
            options={
                'verbose_name': 'Currency Exchange Rate',
                'verbose_name_plural': 'Currency Exchange Rates',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('cost_per_unit_sdg', models.DecimalField(decimal_places=2, help_text='Base purchase cost in SDG', max_digits=15)),
                ('waste_percentage', models.DecimalField(decimal_places=2, help_text='Waste percentage', max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('market_data', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cnf_product', to='core.marketdata')),
            ],
            options={
                'verbose_name': 'CNF Product',
                'verbose_name_plural': 'CNF Products',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='OperationCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cleaning', models.DecimalField(decimal_places=2, help_text='Cleaning cost in SDG', max_digits=10)),
                ('empty_bags', models.DecimalField(decimal_places=2, help_text='Empty bags cost in SDG', max_digits=10)),
                ('printing', models.DecimalField(decimal_places=2, help_text='Printing cost in SDG', max_digits=10)),
                ('handling', models.DecimalField(decimal_places=2, help_text='Handling cost in SDG', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='operation_costs', to='core.product')),
            ],
            options={
                'verbose_name': 'Operation Cost',
                'verbose_name_plural': 'Operation Costs',
            },
        ),
        migrations.CreateModel(
            name='LocalTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transport_to_port', models.DecimalField(decimal_places=2, help_text='Cost of transport to Port Sudan in SDG', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='local_transports', to='core.product')),
            ],
            options={
                'verbose_name': 'Local Transport',
                'verbose_name_plural': 'Local Transports',
            },
        ),
        migrations.CreateModel(
            name='GovernmentCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paperwork', models.DecimalField(decimal_places=2, help_text='Government paperwork in SDG', max_digits=10)),
                ('customs_duty', models.DecimalField(decimal_places=2, help_text='Customs duty in SDG', max_digits=10)),
                ('clearance', models.DecimalField(decimal_places=2, help_text='Clearance cost in SDG', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='government_costs', to='core.product')),
            ],
            options={
                'verbose_name': 'Government Cost',
                'verbose_name_plural': 'Government Costs',
            },
        ),
        migrations.CreateModel(
            name='CNFPriceCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=255)),
                ('total_cost_sdg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_cost_usd', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fob_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cnf_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('exchange_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cnf_calculations', to='core.product')),
            ],
            options={
                'verbose_name': 'CNF Price Calculation',
                'verbose_name_plural': 'CNF Price Calculations',
                'ordering': ['-calculation_date'],
            },
        ),
        migrations.CreateModel(
            name='InternationalTransport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('China', 'China'), ('UAE', 'UAE'), ('Mersing', 'Mersing'), ('India', 'India'), ('Port Sudan', 'Port Sudan'), ('Other', 'Other')], help_text='Destination country', max_length=255)),
                ('freight_cost_usd', models.DecimalField(decimal_places=2, help_text='Freight cost in USD', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_transports', to='core.product')),
            ],
            options={
                'verbose_name': 'International Transport',
                'verbose_name_plural': 'International Transports',
                'ordering': ['product', 'destination'],
                'unique_together': {('product', 'destination')},
            },
        ),
    ]
