# Generated by Django 5.1.7 on 2025-03-11 01:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_currencyexchange_product_operationcost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cost_per_unit_sdg', models.DecimalField(decimal_places=2, max_digits=15)),
                ('waste_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cleaning', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('empty_bags', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('printing', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('handling', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('paperwork', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customs_duty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('clearance', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('transport_to_port', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exchange_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('had_market_data', models.BooleanField(default=False)),
                ('market_data_name', models.CharField(blank=True, max_length=255, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history_records', to='core.product')),
            ],
            options={
                'verbose_name': 'Product History',
                'verbose_name_plural': 'Product History',
                'ordering': ['-created_at'],
            },
        ),
    ]
