# Generated by Django 5.1.7 on 2025-03-11 01:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_producthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='cleaning_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='clearance_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='customs_duty_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='empty_bags_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='handling_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='international_transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='is_current',
            field=models.BooleanField(default=True, help_text='Whether this is the current active calculation'),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='is_manual_override',
            field=models.BooleanField(default=False, help_text='Whether this calculation was manually overridden'),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='local_transport_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='paperwork_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='parent_calculation',
            field=models.ForeignKey(blank=True, help_text='Previous calculation this was based on', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_calculations', to='core.cnfpricecalculation'),
        ),
        migrations.AddField(
            model_name='cnfpricecalculation',
            name='printing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='ProductHistory',
        ),
    ]
